# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use
# this file except in compliance with the License. A copy of the License is
# located at
#
# http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
version: '3.5'
services:
  ubuntu_18.04_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./ubuntu
      dockerfile: 18.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_18.04_OpenSSL_1_1_1-stable
  ubuntu_18.04_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./ubuntu
      dockerfile: 18.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_18.04_OpenSSL_1_1_0-stable
  ubuntu_18.04_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./ubuntu
      dockerfile: 18.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_18.04_OpenSSL_1_0_2-stable
  ubuntu_16.04_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./ubuntu
      dockerfile: 16.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_16.04_OpenSSL_1_1_1-stable
  ubuntu_16.04_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./ubuntu
      dockerfile: 16.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_16.04_OpenSSL_1_1_0-stable
  ubuntu_16.04_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./ubuntu
      dockerfile: 16.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_16.04_OpenSSL_1_0_2-stable
  ubuntu_14.04_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./ubuntu
      dockerfile: 14.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_14.04_OpenSSL_1_1_1-stable
  ubuntu_14.04_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./ubuntu
      dockerfile: 14.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_14.04_OpenSSL_1_1_0-stable
  ubuntu_14.04_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./ubuntu
      dockerfile: 14.04/Dockerfile
    image: ${REPOSITORY_URI}:ubuntu_14.04_OpenSSL_1_0_2-stable
  amazonlinux_2018.03_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./amazonlinux
      dockerfile: 2018.03/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2018.03_OpenSSL_1_1_1-stable
  amazonlinux_2018.03_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./amazonlinux
      dockerfile: 2018.03/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2018.03_OpenSSL_1_1_0-stable
  amazonlinux_2018.03_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./amazonlinux
      dockerfile: 2018.03/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2018.03_OpenSSL_1_0_2-stable
  amazonlinux_2.0_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./amazonlinux
      dockerfile: 2.0/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2.0_OpenSSL_1_1_1-stable
  amazonlinux_2.0_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./amazonlinux
      dockerfile: 2.0/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2.0_OpenSSL_1_1_0-stable
  amazonlinux_2.0_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./amazonlinux
      dockerfile: 2.0/Dockerfile
    image: ${REPOSITORY_URI}:amazonlinux_2.0_OpenSSL_1_0_2-stable
  centos_7_OpenSSL_1_1_1-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_1-stable
      context: ./centos
      dockerfile: 7/Dockerfile
    image: ${REPOSITORY_URI}:centos_7_OpenSSL_1_1_1-stable
  centos_7_OpenSSL_1_1_0-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_1_0-stable
      context: ./centos
      dockerfile: 7/Dockerfile
    image: ${REPOSITORY_URI}:centos_7_OpenSSL_1_1_0-stable
  centos_7_OpenSSL_1_0_2-stable:
    build:
      args:
        OPENSSL_TAG: OpenSSL_1_0_2-stable
      context: ./centos
      dockerfile: 7/Dockerfile
    image: ${REPOSITORY_URI}:centos_7_OpenSSL_1_0_2-stable
